services:
  - type: web
    name: nursesmed
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install && npm run build
      php artisan migrate --force
    startCommand: php -S 0.0.0.0:8080 -t public
